// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvkbuvjrigtlcqxwopxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2a2J1dmpyaWd0bGNxeHdvcHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MjU0MzcsImV4cCI6MjA2ODMwMTQzN30.DCIXdsCC4hKUogS2R_pzPu_hvDHGAkY1shb-8YT1-zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});